# Generated by Django 5.1.1 on 2024-09-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways_app', '0002_train_booking'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
